name: smart_spend_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  drift: ^2.22.1  
  drift_flutter: ^0.2.2
  file_picker: ^8.1.4
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  go_router: ^14.6.2
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  intl: ^0.20.1
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  share_plus: ^11.0.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  drift_dev: ^2.22.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_smart_icon_morado.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_blanco.png
  android_12:
    image: assets/images/splash_blanco.png
    color: "#FFFFFF"